create-game:
  users:
    - username: aropan
      # strategy: 6

    # - query: top
    #   sources:
    #     - contest: round2
    #       number: 20
    #     - contest: sandbox
    #       number: 10
    #       without: finals

    # - query: random
    #   users:
    #     - username: Romka
    #     - username: TonyK
    #     - username: HiPravin
    #     - username: StarWix
    #     - username: Leos
    #     - username: karliso

    # - query: suggest

  formats:
    # - 4x1$${"preset":"Round1"}
    # - 4x1$${"preset":"Round2"}
    - 2x1$${"preset":"Finals"}


find-games:
  attributes: '{"preset":"Finals"}'
  datetime_from: '27 Dec'
  # rank: 2
  contest: finals
  games:
    headers:
      - url
      - rank
      - strategy
      - score
    alignment:
      score: r
      strategy: l
    # sort:
    #   by: time
    #   reverse: false
  statistics:
    headers:
      - user
      - win
      - total
      - n_win
      - n_lose
    alignment:
      user: l
  # return_data: true

win-rates:
  sources:
    - contest: finals
      number: 10
  headers:
    - user
    - win
  sort:
    by: win
    reverse: true
