# create-game
users:
  - username: aropan
    # strategy: 6
  - query: top
    contest: round2
    number: 50
  # - query: suggest
  # - query: suggest

formats:
  # - 4x1$${"preset":"Round1"}
  # - 4x1$${"preset":"Round2"}
  - 2x1$${"preset":"Finals"}
