# create-game
users:
  - username: aropan
    # strategy: 6

  - query: top
    sources:
      - contest: round2
        number: 50
      - contest: sandbox
        number: 10
        without: finals

  # - query: random
  #   users:
  #     - username: Commandos
  #     - username: Recar
  #     - username: GreenTea
  #     - username: Romka

  # - query: suggest

formats:
  # - 4x1$${"preset":"Round1"}
  # - 4x1$${"preset":"Round2"}
  - 2x1$${"preset":"Finals"}
